project:
  type: website
  output-dir: docs

website:
  title: "SQL Fundamentals"
#  favicon: images/beer-mug-icon.png
  page-footer:
    center: |
      <a href="https://clickityklein.github.io/Carl-Klein/">About Carl Klein</a>
    background: primary
    
  navbar:
    left:
# index is automatically included under the main title page
#      - href: index.qmd
#        text: "About"
      - href: week_1.qmd
        text: "The Basic SELECT"
      - href: week_2.qmd
        text: "Group Functions and SubQueries"
    right:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/clickityKlein/SQL
          - text: "Carl Klein's Main Page"
            href: https://github.com/clickityKlein

format:
  html:
    email-obfuscation: javascript
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    citations-hover: true
    code-link: true
    code-fold: true
    theme: flatly
    css: styles.css
    code-block-border-left: primary
    toc: true